### ISSUE TITLE
Update React Native

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#5534]
The current react native version doesn't build in XCode 15 without a hacky workaround. We want to upgrade React Native so it builds with the current xcode version and get the team upgrade as well. 

Upgrade will need thorough QA on multiple OS versions as this is very wide reaching.

XCode 15 also requires a Mac running macOS Ventura 13.5 or later, so that will also need to be confirmed

[More context in slack](https://adhoc.slack.com/archives/C0212B872MT/p1700581727609239)

Specific context about the version from Slack:

> Ok, for my Liz, check out which react-native version builds on both Xcode 15 & 14 task, I have an update: I installed the latest bug fix for react-native 0.71 (which fyi is 0.71.14) and as long as your xcodebuild version is the same as the Xcode version you're targeting, it will run and build in both Xcode 14.x & 15.x. (You can see your xcodebuild version by running xcodebuild -version in your terminal. Just make sure it matches the Xcode version you're using before pod install and yarn bundle:ios and it's fine - I think my personal issue was that I have both 14.x and 15.x installed, so the build version was set differently for the version I was trying to run it in, if you only have one version installed (like a normal person :laugh-cry:) it shouldn't be an issue).
As for upgrading to the next big version of react-native (0.72.x)... that's... more complicated. But just going to 0.71.14 to grab the Xcode bug fix was fairly painless if that's something we want to consider.

**Comment by timwright12** [comment]
@Sparowhawk we did this, right?

**Comment by DJUltraTom** [comment]
an RC test run is a pretty solid smoke test, so we're giving it a shake, Appears that the android test run is failing, not sure if its a testing failure or an issue with the build. Investigating further

**Comment by Sparowhawk** [comment]
@DJUltraTom I updated the branch with develop. that should fix all the android stuff. Is this one ready to merge?

**Comment by bischoffa** [comment]
@Sparowhawk @DJUltraTom is out today for [jury duty](https://adhoc.slack.com/archives/CU2Q76NPR/p1702512422012249)

**Comment by bischoffa** [comment]
Looking at TestRails I don't think testing was done. I see activity from Tom yesterday but it was for the release.   
 

![](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/116006847/aec7effd-383c-4a87-a600-48f79ae6a78b)

**Comment by timwright12** [comment]
@bischoffa that was the test run Tom did, the github action for testrail integration is pointing at the release right now, it needs to be updated. Probably need another way to test or just to enter it manually for now

**Comment by bischoffa** [comment]
Still getting familiar with TestRails and what it means.  This is all I know as of now per Dylan's question if testing was done.  Hopefully Tom will be back tomorrow to provide more details.

**Comment by DJUltraTom** [comment]
The test rail cases that had actions on it from weds was not related to testing the RN updates. 
Current test pass with detox artifacts (thanks @rbontrager ) is here:
https://dsvavsp.testrail.io/index.php?/runs/view/5053&group_by=cases:section_id&group_order=asc

**Comment by Sparowhawk** [comment]
/Users/runner/work/va-mobile-app/va-mobile-app/VAMobile/ios/Pods/Headers/Public/Flipper-Folly/folly/portability/Config.h:20:10: 'folly/folly-config.h' file not found

#include <folly/folly-config.h>

This is the current error in the testrail run for iOS

I have tried the following:

Full clean (remove node modules, remove pods, remove ios/build folder, cleared derived data, and rebuilt from scratch)
latest flipper folly, 0.164, 0.163, and the current 0.125 versions
reverted entire podfile to what we currently have
reverted podfile with the different versions of flipper folly
tried adding things to gitignore
also tried -DFOLLY_NO_CONFIG adding this flag

The issue is this error above is preventing the archiving of the app in CI. It has something to do with the podfile, RN version, flipper folly, and xcode. It may be the RN version is to new for the xcode version that is used by CI.

**Comment by DJUltraTom** [comment]
test run completed, this is a test run for the manual portion of the react native update tests, the previous test run mysteriously disappeared.:
https://dsvavsp.testrail.io/index.php?/runs/view/5081&group_by=cases:section_id&group_order=asc

**Comment by DJUltraTom** [comment]
on the overnight build, I verified I can log into the app, spot checked a bit, everything is looking good, closing as deployed
