### ISSUE TITLE
Apply Use Focus Effect to Home Screen

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7485]
AC:

- When a user focuses on the home screen, all Personalization APIs (Secure Message, Appointments, Claims & Appeals, and Prescriptions) should be reloaded

**Comment by TKDickson** [comment]
@theodur things I'm noticing, testing with karsyn:
* We're running the appointments and Rx APIs on the sync screen, and then running them again immediately once the home screen loads. Is there a way to move/remove API calls to get rid of that duplication?
* The claims call for Karsyn is NOT running on the sync screen, but is running (and failing) on the home screen. I'm not sure which of those is correct -- are we not calling claims when we should on the sync screen, or are we incorrectly calling it on the home screen? Karysn is authorized for appeals, but not claims, according to authorizedServices.
* After the home screen loads, there's a significant delay before any action I take will be reflected in the app (~6 seconds on Android, and ~42 seconds on iOS). It's probably the thing I've seen before, where we get some errors back immediately from the backend but it freezes the front end for several seconds, but that's very concerning to happen on the home screen, especially since the problem is opaque to veterans.

**Comment by TKDickson** [comment]
Noticing, testing with +54:
* Claims isn't reloading/resending when I go back to the home screen. The API fires the first time I'm on the home screen, and again when I go to the claims list, but not at each HS load.

**Comment by theodur** [comment]
@TKDickson Nice finds; to answer your questions:

> We're running the appointments and Rx APIs on the sync screen, and then running them again immediately once the home screen loads. Is there a way to move/remove API calls to get rid of that duplication?

Binny has a [ticket](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7300) he's working on for removing API calls from the sync screen, but that won't include appointments and RX, since his ticket will be based off and merged into `develop`. I can remove the appointment and RX API calls on the sync screen in my branch to follow that trend. Definitely not ideal to have successive calls like that.

> The claims call for Karsyn is NOT running on the sync screen, but is running (and failing) on the home screen. I'm not sure which of those is correct -- are we not calling claims when we should on the sync screen, or are we incorrectly calling it on the home screen? Karysn is authorized for appeals, but not claims, according to authorizedServices.

After looking at the code, it doesn't look like there's a check if the user is authorized for the service before making the API call, which is probably the issue. This is also the case for the other API calls on the home screen. I'll need to add a check for all of those API calls.

> After the home screen loads, there's a significant delay before any action I take will be reflected in the app (~6 seconds on Android, and a whopping ~42 seconds on iOS). It's probably the thing I've seen before, where we get some errors back immediately from the backend but it freezes the front end for several seconds, but that's very concerning to happen on the home screen, especially since the problem is opaque to veterans.

Yeah it seems like this could be related to the unauthorized API call failures. I'll see if I can reproduce, and if adding the authorized services checks resolve that issue

**Comment by theodur** [comment]
> Claims isn't reloading/resending when I go back to the home screen. The API fires the first time I'm on the home screen, and again when I go to the claims list, but not at each HS load.

Strange, and that's only for claims? The other API calls fire when going back to the home screen? 🤔

**Comment by TKDickson** [comment]
@theodur thanks for answering/looking into the first three! 

For the last one, yes - the API call is not happening on home screen reload with claims only (prescriptions and appointments fire again), which is very odd.

**Comment by theodur** [comment]
@TKDickson No problem! The first two issue should be resolved now, changes have been merged into the branch. Unfortunately, I wasn't able to reproduce the third issue with the screen being frozen, but I'm hoping the cause of it was the unauthorized API calls. Let me know if the frozen screen issue is fixed for you 🤞

I also fixed the issue with the claims API call not be made on subsequent trips to the home screen. I had to add a `forceRefetch` option to the claim API function call

**Comment by TKDickson** [comment]
Alright - @theodur with the updated build, here's where things stand:
* No calls are firing on the sync screen - fixed!
* Claims is firing again upon returning to home screen - fixed!
* However, the claims module never shows up. Womp womp. Can see this problem with both +54 and judy.morrison. - broken
* I misunderstood your intention yesterday. "Claims" on the home screen encompasses both claims AND appeals, so we should still be making the call even if veterans are only authorized for one of those areas. -- needs updating, although arguably we could leave it be until the official "error and edge case" handling ticket comes through.
* We're inevitably going to run into that 6 second/42 second freeze again, when we re-enable the API call. I'll bring it up at grooming today, see what Ameet thinks. (The larger question of "things that are pre-existing with the app that were maybe fine/less urgent when on a subpage are a BIG DEAL on the homepage, when/how would you like to tackle them")

**Comment by theodur** [comment]
@TKDickson Good catch about the claims module not showing up. I just fixed that, should be working now (tested with Judy).

And good point about users with access to appeals but not claims. I went ahead and updated the logic to fetch claims and appeals if a user has access to either claims or appeals

**Comment by TKDickson** [comment]
All set - claims, prescriptions and appointments modules all show up on the home screen, and the APIs are called each time the home screen is accessed (no matter the different paths I used to get there). Karsyn is still showing the behavior in bug ticket #7746, but at least the claims API is being called thanks to the logic update.

Approved to merge into XL.

**Comment by TKDickson** [comment]
Merged to XL, closing.
