### ISSUE TITLE
BUG - sev-3 - iOS - Appointments: "add to calendar" does nothing

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8788]
## What happened?

On iOS only (Android fine), the 'add to calendar' link for upcoming appointments [just.... doesn't do anything](https://drive.google.com/file/d/1KLcqLVkyWEIeskESduAA9Jm-9fwgGGDE/view?usp=sharing).

Seeing this on today's develop build (and found while testing #6868, but not caused by that since it's also in develop)

## Specs:

- Device: iPhone 12 on iOS 17
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by Sparowhawk** [comment]
@TKDickson couple of questions. What user and appt is this? Does your iOS device have the calendar permission?

**Comment by TKDickson** [comment]
@Sparowhawk 
* I saw this in demo mode with all appointments I tried, as well as john.morrison with all appointments I tried.
* For permissions, I never got a prompt to allow calendar, so I can't tell you whether they had them or not at the time. Which could very well be the issue - that we are trying to do some calendar thing but permissions aren't popping up.

**Comment by Sparowhawk** [comment]
@TKDickson I just went through and tested pretty close to every appt for both of those and was able to get the calendar pop up to occur from clicking on the button. I also turned off the calendar permission and clicked the button and it correctly displayed the popup to send them to settings.

I took a look on the Apple forums and it looks this issue started on iOS 17 and may be present in iOS 17.1

iOS 17.2+ the issue has been fixed according to the forums

**Comment by Sparowhawk** [comment]
@rbontrager can you confirm that this works on iOS 17.2+ for iOS so that we can close this issue?

**Comment by TKDickson** [comment]
Reassigning to me, I'll upgrade my device and see if it's fixed.

**Comment by TKDickson** [comment]
Alright - @Sparowhawk sadly I'm still seeing this with my device (which is on 17.3.1). Here's a [video going through several of Judy's appointments](https://drive.google.com/file/d/16pXDJSjdGlGC8caG4BvZkTNj5u5MOZeg/view?usp=sharing) with the 6/18 develop build. Moving this back to.... current sprint work.

**Comment by Sparowhawk** [comment]
@TKDickson There has to be some issue on your device with permissions or something.

I have this working on 17.2 here


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3R6QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02de1b02ce10d79f279e619b4fa774625c900618/Screen%20Recording%202024-06-18%20at%203.37.04%E2%80%AFPM.mov)

**Comment by TKDickson** [comment]
@Sparowhawk that looks like an emulator, do you have a physical iOS device on a 17.2 or higher version of iOS that you've tried this? I'll also ask the other folks in QA to try on their devices and loop you into that slack thread.

**Comment by Sparowhawk** [comment]
tried on 17.4.1 and it works on my physical device

**Comment by TKDickson** [comment]
Also worked on Rachael's iOS devices - I'll close, and if I figure out what about my iOS is making this wonky, will reopen.
